name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install git
        run: |
          sudo apt install -y git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync
      - name: Lint with Ruff
        run: |
          uv run ruff check --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          uv run pytest --cov job_helper -xs .
      - name: Generate Coverage Report
        run: |
          uv run coverage report -m
